name: Check PR

on:
  pull_request:

jobs:

  lint-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run lint:css

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run lint:js

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npx playwright install --with-deps
      - run: npm run test:e2e

  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build-storybook

  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build
