name: Prettier

on:
  push:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.1
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run prettier
      - name: Create or Update PR
        run: |
          BASE_BRANCH=$( git rev-parse --abbrev-ref HEAD )
          HEAD_BRANCH="prettier/$BASE_BRANCH"
          git config --global user.email "cicada1003@gmail.com"
          git config --global user.name "FineArchs"
          git add .
          git commit -m"prettier $BASE_BRANCH"
          git branch -m $HEAD_BRANCH
          git push -f -u origin $HEAD_BRANCH
          PRS=$(gh pr list --json id -head $HEAD_BRANCH -s open)
          if [ "$PRS" == '[]' ]
          then
            gh pr create --base $BASE_BRANCH --fill --label bot
          fi
