name: Stage

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build-app-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.4
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}-18
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: app-dev
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-app-dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-dev
          path: dist
      - uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: beta
          keep_files: true
